### ISSUE TITLE
OnDeath() never called

### ISSUE THREAD

**Issue by MichaelEpicA** [All-Of-Us-Mods/MiraAPI#11]
In the modifier, there is a function called OnDeath(), this function is never actually called. There are 0 references to OnDeath in the MiraAPI.

**Comment by ang-xd** [comment]
We are aware of this. It's an oversight on my side. Will be fixed soon.

**Comment by MichaelEpicA** [comment]
Thanks for the heads up!

**Comment by XtraCube** [comment]
first issue lol, solved by 8178967
